sudo: required
services:
  - docker
language: go
go:
  - '1.7'
script:
  - make test
before_deploy:
  - GOOS=linux GOARCH=amd64 make
deploy:
  provider: script
  skip_cleanup: true
  script: DOCKER_IMAGE_TAG=test make ci-docker-release
  on:
    branch: dtan4/test
    go: '1.7'
